steps:
  - name: node:10.15.1
    dir: 'edge'
    entrypoint: npm
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'GH_ACCESS_TOKEN=${_GH_ACCESS_TOKEN}'
    dir: 'edge'
    args: ['app', 'deploy']
timeout: '1600s'
